const actionTypes = {
    SET_LOAD_SAL: "SET_LOAD_SAL",
    SET_LOAD_ORD: "SET_LOAD_ORD",
    SET_LOAD_REF: "SET_LOAD_REF",
    SET_LOAD_LOG: "SET_LOAD_LOG",

    SET_UNLOAD_SAL: "SET_UNLOAD_SAL",
    SET_UNLOAD_ORD: "SET_UNLOAD_ORD",
    SET_UNLOAD_REF: "SET_UNLOAD_REF",
    SET_UNLOAD_LOG: "SET_UNLOAD_LOG",

    BIG_DATA_WB: "BIG_DATA_WB",
}

export default actionTypes;